// lib/pdf/buildRequestPdf.ts
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { safe } from "./helpers";

/**
 * Build a clean request PDF report.
 * @param req Full request object including customer, vehicle, parts, notes, photos
 */
export async function buildRequestPdf(req: any): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();

  const page = pdf.addPage([612, 792]); // Letter size
  const { width } = page.getSize();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const titleFont = await pdf.embedFont(StandardFonts.HelveticaBold);
  let y = 750;

  function text(txt: string, size = 12, bold = false) {
    page.drawText(txt, {
      x: 40,
      y,
      size,
      font: bold ? titleFont : font,
      color: rgb(0, 0, 0),
    });
    y -= size + 6;
  }

  /* ================================
      HEADER
  =================================== */

  text(`Service Request Report`, 18, true);
  text(`Request ID: ${req.id}`);
  y -= 10;

  /* ================================
      CUSTOMER / VEHICLE
  =================================== */

  text("Customer Information", 14, true);
  text(`Name: ${safe(req.customer?.name)}`);
  y -= 10;

  text("Vehicle Information", 14, true);
  const v = req.vehicle || {};
  text(`Year/Make/Model: ${safe(v.year)} ${safe(v.make)} ${safe(v.model)}`);
  text(`Unit: ${safe(v.unit_number)}  Plate: ${safe(v.plate)}`);
  y -= 10;

  /* ================================
      SERVICE DETAILS
  =================================== */

  text("Service Details", 14, true);
  text(`Status: ${safe(req.status)}`);
  text(`Service: ${safe(req.service)}`);
  text(`Mileage: ${safe(req.mileage)}`);
  text(`PO#: ${safe(req.po || req.po_number)}`);
  text(`FMC: ${safe(req.fmc)}`);
  y -= 10;

  /* ================================
      NOTES
  =================================== */

  if (req.notes?.length) {
    text("Notes", 14, true);
    for (const n of req.notes) {
      text(`• ${n.body}`);
    }
    y -= 10;
  }

  /* ================================
      PARTS
  =================================== */

  if (req.parts?.length) {
    text("Parts Used", 14, true);
    for (const p of req.parts) {
      text(`• ${safe(p.part_name)} (${safe(p.part_number)})`);
    }
    y -= 10;
  }

  /* ================================
      PHOTOS (thumbnails)
  =================================== */

  if (req.photos?.length) {
    text("Photos", 14, true);

    let x = 40;
    let rowY = y;

    for (const p of req.photos) {
      try {
        const bytes = await fetch(p.url).then((r) => r.arrayBuffer());
        const img = await pdf.embedJpg(bytes);

        page.drawImage(img, {
          x,
          y: rowY - 80,
          width: 100,
          height: 80,
        });

        x += 110;
        if (x > width - 120) {
          x = 40;
          rowY -= 100;
        }
      } catch (_) {
        // ignore if fail
      }
    }

    y = rowY - 110;
  }

  /* ================================
      FOOTER
  =================================== */

  page.drawText("Generated by Revlet", {
    x: 40,
    y: 30,
    size: 10,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  return await pdf.save();
}
