// lib/status/status.ts
export const DB_TO_UI = {
  NEW: "NEW",
  WAITING_APPROVAL: "WAITING_APPROVAL",
  WAITING_PARTS: "WAITING_PARTS",
  SCHEDULED: "SCHEDULED",
  IN_PROGRESS: "IN_PROGRESS",
  RESCHEDULED: "RESCHEDULED",
  CANCELED: "CANCELED",
  COMPLETED: "COMPLETED",
};

export const UI_TO_DB = DB_TO_UI;



